name: CI on Test Environment

on:
  pull_request:
    branches: [develop]
    
jobs:
  build-and-deploy:
    name: Build Image and Deploy to Test Environment
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
#     - name: Build and Push to docker registry
#       uses: elgohr/Publish-Docker-Github-Action@master
#       with:
#         name: ayase252/aquarium
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         snapshot: true
#     - name: Retrieve DigitalOcean kubeconfig
#       uses: digitalocean/action-doctl@master
#       env:
#         DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#       with:
#         args: kubernetes cluster kubeconfig show hina > $GITHUB_WORKSPACE/.kubeconfig
#     - name: Setup kubectl
#       uses: azure/setup-kubectl@v1
#       with:
#         version: v1.16.2
#     - name: Deploy
#       run: |
#        export KUBECONFIG=$KUBECONFIG:$GITHUB_WORKSPACE/.kubeconfig
#        kubectl config use-context do-sgp1-hina
#        kubectl set image deploy/blackbox-backend-test blackbox-backend-test=ayase252/aquarium:${{steps.docker-publisher.outputs.snapshot-tag}}
